In [1]:
import os
import pandas as pd
import collections

In [5]:
data_path = "/work/pi_dhruveshpate_umass_edu/project_19/Data/synthetic_data_Apr25"
file = "news_training.csv"

data = pd.read_csv(os.path.join(data_path, file))
data = data[data.id.notnull()].reindex()
data.reset_index(inplace=True, drop=True)

print(data.shape)
data.head()

(924, 5)

,id,article,entity types,relationships,synthetic article
0,62b1e91ce87f1fc6c056ce9172f5f7c66efba907,By . Lydia Warren . Jerry Sandusky's adopted s...,"[['Jerry Sandusky', 'Person'], ['Matthew Sandu...","[['Matthew Sandusky', 'gave an interview to', ...",In a revealing and emotional interview with Op...
1,ff693482cdd3dfb9e7064f487516b58f20c060ca,"By . Jaymi Mccann . PUBLISHED: . 15:44 EST, 14...","[['Jaymi McCann', 'Person'], ['swimmer', 'Pers...","[['emergency services', 'conduct search and re...","In the scenic Brecon Beacons of Mid Wales, a s..."
2,e9900c3b37b1ca3c0a62d203670f7e0e5ac5da89,By . Michael Zennie . A sightseer who tried to...,"[['Michael Zennie', 'Person'], ['sightseer', '...","[['Grand Prismatic Spring', 'contains', 'bacte...",In the heart of Wyoming lies the Yellowstone N...
3,fe9d8a82cb4122fdd905012becc7418e2d2ff740,Facebook has started collecting information ab...,"[['Facebook', 'Organization'], ['users', 'Conc...","[['Facebook', 'collects information from', 'us...",In a bold move that has stirred up the digital...
4,aceee806bdda590589d85f67401e6a6a2fc46b2f,"By . Deborah Arthurs . PUBLISHED: . 08:32 EST,...","[['Duchess of Cambridge', 'Person'], ['Hobbs',...","[['Duchess of Cambridge', 'wore clothing from'...",In a remarkable display of support for the Bri...

In [18]:
data["processed_entities"] = ""
data["processed_relations"] = ""

for i in data.index:
    ent_list = []
    tmp = eval(data["entity types"][i])
    for item in tmp:
        ent_list.append(item[0])
    data["processed_entities"][i] = "; ".join(ent_list)
    
    rel_list = []
    tmp = eval(data["relationships"][i])
    for item in tmp:
        rel_list.append(" | ".join(item))
    data["processed_relations"][i] = "\n".join(rel_list)
    
    # print(type(tmp), rel_list, "\n".join(rel_list))
    # break

In [19]:
data.head()

,id,article,entity types,relationships,synthetic article,processed_entities,processed_relations
0,62b1e91ce87f1fc6c056ce9172f5f7c66efba907,By . Lydia Warren . Jerry Sandusky's adopted s...,"[['Jerry Sandusky', 'Person'], ['Matthew Sandu...","[['Matthew Sandusky', 'gave an interview to', ...",In a revealing and emotional interview with Op...,Jerry Sandusky; Matthew Sandusky; Oprah Winfre...,Matthew Sandusky | gave an interview to | Opra...
1,ff693482cdd3dfb9e7064f487516b58f20c060ca,"By . Jaymi Mccann . PUBLISHED: . 15:44 EST, 14...","[['Jaymi McCann', 'Person'], ['swimmer', 'Pers...","[['emergency services', 'conduct search and re...","In the scenic Brecon Beacons of Mid Wales, a s...",Jaymi McCann; swimmer; emergency services; pol...,emergency services | conduct search and rescue...
2,e9900c3b37b1ca3c0a62d203670f7e0e5ac5da89,By . Michael Zennie . A sightseer who tried to...,"[['Michael Zennie', 'Person'], ['sightseer', '...","[['Grand Prismatic Spring', 'contains', 'bacte...",In the heart of Wyoming lies the Yellowstone N...,Michael Zennie; sightseer; Yellowstone; Grand ...,Grand Prismatic Spring | contains | bacteria\n...
3,fe9d8a82cb4122fdd905012becc7418e2d2ff740,Facebook has started collecting information ab...,"[['Facebook', 'Organization'], ['users', 'Conc...","[['Facebook', 'collects information from', 'us...",In a bold move that has stirred up the digital...,Facebook; users; social media site; privacy po...,Facebook | collects information from | users\n...
4,aceee806bdda590589d85f67401e6a6a2fc46b2f,"By . Deborah Arthurs . PUBLISHED: . 08:32 EST,...","[['Duchess of Cambridge', 'Person'], ['Hobbs',...","[['Duchess of Cambridge', 'wore clothing from'...",In a remarkable display of support for the Bri...,Duchess of Cambridge; Hobbs; Celeste coat; Liv...,Duchess of Cambridge | wore clothing from | Ho...

In [ ]:
data["processed_entities"] = ""
data["processed_relations"] = ""

for i in data.index:
    ent_list = []
    tmp = eval(data["entity types"][i])
    for item in tmp:
        ent_list.append(item[0])
    data["processed_entities"][i] = "; ".join(ent_list)
    
    rel_list = []
    tmp = eval(data["relationships"][i])
    for item in tmp:
        rel_list.append(" | ".join(item))
    data["processed_relations"][i] = "\n".join(rel_list)
    
    # print(type(tmp), rel_list, "\n".join(rel_list))
    # break